### ISSUE TITLE
Will you release the dataset?

### ISSUE THREAD

**Issue by cdowen** [mfaisal59/RBSF#1]
Hi, I follow the motion segmentation task from the original MPNet to your impressive work. The results are great and I think the dataset must help a lot for me since there is no large scale realistic dataset currently for motion segmentation.
So I really want to know when will you release the dataset? I can use it to improve my research model. Thanks in advance.

**Comment by mfaisal59** [comment]
Hi,
Thank you for showing interest. We have uploaded the links to download RBSF dataset, you can now download the dataset.
